### ISSUE TITLE
Rules overview on website: Showing Composite & Atomic rules in hierarchy

### ISSUE THREAD

**Issue by jkodu** [auto-wcag/auto-wcag#174]
- Parent-Child hierarchy? 
- come up with a design?

**Comment by annethyme** [comment]
@jkodu, I created this lovely prototype in Word with a proposal for how we can (hopefully easily) show the relation between Composite rules and their atomic rules:  
![image](https://user-images.githubusercontent.com/15611692/47221663-54337580-d3b5-11e8-8f2e-09b6feb863d8.png)

Since accessibility has to be a main concern when we build this, there is a limit to how fancy we can be without making it really hard for us to communicate the relations between things programatically.

**Comment by jkodu** [comment]
@annethyme - I like this representation. 

The only problem is the introduction of multiple columns. I may nest the tables for the atomic rules. 

Either way, I would need this PR merged before - https://github.com/auto-wcag/auto-wcag/pull/291

**Comment by annethyme** [comment]
@jkodu, isn't this already implemented?
