### ISSUE TITLE
Form field has non-empty accessible name - Input nested into a label with for attribute pointing to a non-existing element

### ISSUE THREAD

**Issue by giacomo-petri** [auto-wcag/auto-wcag#1893]
Hello,

I’ve a question about a specific scenario, referring to [Form field has non-empty accessible name](https://www.w3.org/WAI/standards-guidelines/act/rules/e086e5/) 

### Example:
```
<label for="first-name">
    <span>First name</span>
    <input type="text" name="fn" value="">
</label>
```

### Properties:
- label containing input (sufficient technique)
- label with for attribute pointing to a non-existing element (insufficient technique)

### Thoughts:
For sure it's not something I would recommend (:D), but as existing scenario, I'm very conflicted about how to treat it (failure or not?).

Per Moz reference ([&lt;label&gt;: The Input Label element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label)):

> Note: A &lt;label&gt; element can have both a for attribute and a contained control element, as long as the for attribute points to the contained control element.

But I'm not able to find anything similar in HTML specs; in particular, in [4.10.4 The label element](https://html.spec.whatwg.org/multipage/forms.html#the-label-element), specs state:

> The label element represents a caption in a user interface. The caption can be associated with a specific form control, known as the label element's labeled control, either using the for attribute, or by putting the form control inside the label element itself.
> 
> Except where otherwise specified by the following rules, a label element has no labeled control.
> 
> The for attribute may be specified to indicate a form control with which the caption is to be associated. If the attribute is specified, the attribute's value must be the ID of a labelable element in the same tree as the label element. If the attribute is specified and there is an element in the tree whose ID is equal to the value of the for attribute, and the first such element in tree order is a labelable element, then that element is the label element's labeled control.
> 
> If the for attribute is not specified, but the label element has a labelable element descendant, then the first such descendant in tree order is the label element's labeled control.

The highlighted case seems not fully covered. Specs clearly state:

> If the attribute is specified, the attribute's value must be the ID of a labelable element in the same tree as the label element.

But doesn't clearly specify what should happen if the element with this specific ID does not exist and if a "fallback" is present (such as wrapping the input within the label). 

That said, if we run the snippet of code above in the w3 validator, it returns a parsing issue: 

> Any input descendant of a label element with a for attribute must have an ID value that matches that for attribute.

Assuming from above that having a label that is pointing to an element that doesn't exist is not allowed by specs, is it fair to say that it's a 4.1.2 failure, even if the input is wrapped within its label?

In addition, browsers seem render this scenario in different ways; for example both Chrome and Firefox provide an empty acc name. Safari instead provides "First name" as acc name.

Attached an in-progress test: [input-empty-acc-name.html.zip](https://github.com/act-rules/act-rules.github.io/files/9122450/input-empty-acc-name.html.zip)

What do you think about it?

Aside note:
If we feel it's an issue, should we add something in [Form field has non-empty accessible name](https://www.w3.org/WAI/standards-guidelines/act/rules/e086e5/) assumptions?

Giacomo

**Comment by Jym77** [comment]
> Per Moz reference ([<label>: The Input Label element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label)):
> 
> > Note: A <label> element can have both a for attribute and a contained control element, as long as the for attribute points to the contained control element.

> That said, if we run the snippet of code above in the w3 validator, it returns a parsing issue:
> 
> > Any input descendant of a label element with a for attribute must have an ID value that matches that for attribute.

That is… interesting.

When the `for` attribute points to an existing element, this is exactly the case handled by [Step 2C of accessible name computation](https://w3c.github.io/accname/#step2C) (control embedded within the label of another control) ([Step 2E in working draft](https://www.w3.org/TR/accname-1.2/#step2E)). 
See, for example, [this testable statement](https://www.w3.org/wiki/AccName_1.1_Testable_Statements#Name_file-label-embedded-select):
```
if given
  <input type="file" id="test" />
  <label for="test">Flash the screen 
    <select size="1">
      <option selected="selected">1</option>
      <option>2</option>
      <option>3</option>
    </select>
    times.
  </label>
then the accessible name of the element with id of "test" is "Flash the screen 1 times."
```
Here, the `label` embeds a labellable `select`, but has a `for` attribute pointing to the `input` 🤔 

Not really helping with the question here. But it is interesting that name computation consider this as a valuable construction (and I can see why the patterns help builds a better name) while the validator would reject it…

**Comment by Jym77** [comment]
Side note: Checking with Validator why they flag these: https://github.com/validator/validator/issues/1403

**Comment by Jym77** [comment]
So, it is indeed invalid HTML (as pointed in the [Content model of `label`](https://html.spec.whatwg.org/multipage/forms.html#the-label-element:concept-element-content-model)), and the accname computation has an issue on the topic: https://github.com/w3c/accname/issues/154

In that case, following specs, there is no labeled control (the `for` does not points to a valid ID, which is already bad in itself, but then none of the cases work since nested labellable is only used when `for` is not specifed). Browsers may behave differently.

Given that it is not valid HTML, I'm somewhat not concerned by the outcome of the rule (both current and what it should be) 😁 Essentially, this is failing 4.1.1 in the first place.

**Comment by giacomo-petri** [comment]
Before closing this one, based on https://github.com/w3c/accname/issues/154, do we want to add 2 examples to the existing rule (one passing, one failing) highlighting which is the correct approach for input elements that serve as label or part of label for another form element (aria-labelledby)?

Failure:
```
<input type="file" id="test" />
  <label for="test">Flash the screen 
    <select size="1">
      <option selected="selected">1</option>
      <option>2</option>
      <option>3</option>
    </select>
    times.
  </label>
```

Working:
```
<input type="file" aria-labelledby="test" />
  <label id="test">Flash the screen 
    <select size="1">
      <option selected="selected">1</option>
      <option>2</option>
      <option>3</option>
    </select>
    times.
  </label>
```

Or it's just not relevant at all?

**Comment by giacomo-petri** [comment]
\+ I would like to underline few thoughts and I'll do it as they come to my mind, even if they are not strictly related to the ACT-rules activities.

### Parsing issue
> So, it is indeed invalid HTML (as pointed in the [Content model of label](https://html.spec.whatwg.org/multipage/forms.html#the-label-element:concept-element-content-model)), and the accname computation has an issue on the topic: https://github.com/w3c/accname/issues/154
> ...
> Given that it is not valid HTML, I'm somewhat not concerned by the outcome of the rule (both current and what it should be) 😁 Essentially, this is failing 4.1.1 in the first place.

I agree that this is not valid HTML. On the other hand, following the 4th sufficient techniques for [4.1.1 Parsing SC](https://www.w3.org/TR/UNDERSTANDING-WCAG20/ensure-compat-parses.html), it states:

> Ensuring that Web pages can be parsed by using one of the following techniques:
> - [H74: Ensuring that opening and closing tags are used according to specification](http://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/H74) (HTML) AND [H93: Ensuring that id attributes are unique on a Web page](http://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/H93) (HTML) AND [H94: Ensuring that elements do not contain duplicate attributes](http://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/H94) (HTML)
> - [H75: Ensuring that Web pages are well-formed](http://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/H75) (HTML)

In particular:
- [H74: Ensuring that opening and closing tags are used according to specification](http://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/H74) (HTML) - passed
- AND [H93: Ensuring that id attributes are unique on a Web page](http://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/H93) (HTML) - passed
- AND [H94: Ensuring that elements do not contain duplicate attributes](http://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/H94) (HTML) - passed

To me, it seems inconsistent, as this scenario results in a parsing issue that still passes 4.1.1 SC, affecting other criteria such as 4.1.2 Name, Role, Value.


### Consistency with other scenarios
Input type image elements, for example, have many fallbacks in case of missing alternative text (e.g. aria-labelledby, aria-label, alt if usable string, title if usable string, etc.), that are allowed by [HTML Accessibility API Mapping](https://www.w3.org/TR/html-aam-1.0/#input-type-image-accessible-name-computation).
Returning to my snippet of code in first comment
```
<label for="first-name">
    <span>First name</span>
    <input type="text" name="fn" value="">
</label>
```
having a labelable element within a label element, in my opinion, makes it clear that the intent of the developer is to associate the labelable element with the label itself.
Similarly to missing alt for an input type image, this might be considered a sort of fallback, when the for attribute is pointing to a non-existing element.

In addition, if you try to validate the following snippet of code
`<input type="image" src="submit.png" aria-label="Submit form">`
using the [w3 validator](https://validator.w3.org/), returns 

> Element [input](https://html.spec.whatwg.org/multipage/#the-input-element) is missing required attribute alt

even if, per [HTML Accessibility API Mapping](https://www.w3.org/TR/html-aam-1.0/#input-type-image-accessible-name-computation), the accessible name is "Submit form".

@Jym77 , based on your feedback

> Given that it is not valid HTML, I'm somewhat not concerned by the outcome of the rule (both current and what it should be) 😁 Essentially, this is failing 4.1.1 in the first place.

returning to my initial snippet
```
<label for="first-name">
    <span>First name</span>
    <input type="text" name="fn" value="">
</label>
```
which is the difference in terms of parsing between the input type image example and the label containing a labelable element with for attribute pointing to a non-existing element? 
In both cases the w3 validator is generating a parsing issue, so also the HTML Accessibility API Mapping for input type image shouldn't be so much relevant here, as this is failing 4.1.1 in the first place.

**Comment by Jym77** [comment]
The normative text of 4.1.1 does is
>  In content implemented using markup languages, elements have complete start and end tags, elements are nested according to their specifications, elements do not contain duplicate attributes, and any IDs are unique, except where the specifications allow these features. 

H74 cover the bit about correct nesting (Step 3  in the test procedure). So, I would say that a `label` with a `for` pointing elsewhere than the nested labellable does not pass H74 (and certainly does not pass the "elements are nested according to their specifications" bit of 4.1.1).

---
Concerning invalid HTML, I'm less clear 🤔 There are fallbacks in many places, both other specs and browsers implementation.

I don't think that the HTML AAM says that image button don't need a `alt`. I think it just says that `aria-label(ledby)` takes precedence over it for name computation. We can certainly have widgets that are invalid HTML but nonetheless have an accessible name (and so fail 4.1.1 but not 4.1.2) (and in many ways, the easiest would be to duplicate an `id` which is invalid HTML but almost doesn't affect name computation (expect `aria-labelledby`)).

Then the rules take [the accessibility tree](https://www.w3.org/TR/act-rules-aspects/#input-aspects-accessibility) as [input aspect](https://www.w3.org/WAI/standards-guidelines/act/rules/e086e5/#input-aspects), but don't care how it's been computed:
> The means by which the accessibility tree is constructed, be it by a web browser or not, is not of importance as long as the construction follows any applicable specifications that might exist, such as the [Core Accessibility API Mappings 1.1](https://www.w3.org/TR/core-aam-1.1/) [[CORE-AAM-1.1]](https://www.w3.org/TR/act-rules-aspects/#biblio-core-aam-11).

So, for stuff that is not defined in the spec, the rule may pass or fail depending on UA and it doesn't really matter (well, still a bit).

`<input type="image" src="submit.png" aria-label="Submit form">` has a name when the accessibility tree is built according to spec. So do `<button id="button">First</button> <button id="button">Second</button>`. Even through none of them are valid HTML, the HTML problem doesn't interfere with the name computation.

`<label for="invalid">Hello<input /></label>` is slightly different. Specs are not clear whether it should have a name and UA may do more or less what they want. If they behave differently, it certainly deserves an Accessibility Support note. I'm however not sure we should have a Failed test case with it since. Because it might only fail in some UA/AT combinations, and this is not a bug we can report to these UA/AT as the specs don't say how to handle this case. Some browsers may ignore the invalid `for` and treat it as a `label` enclosing a labellable element, which is reasonable fallback. Other may consider that the invalid `for` means there is no controlled element, which is also reasonable (maybe `<input id="invalid">` will appear later and the dev forgot to remove the `for` when hiding it). If we have it as a Failed case (or as a Passed one), we will get inconsistent results between testers and no clear way to decide who is right (because no normative document handle this case). If UA/AT behave differently, this would also fall into our design guideline of [no Accessibility Support test cases](https://act-rules.github.io/pages/design/test-cases/#avoid-accessibility-support-issues).

---
I was today years old when I learnt that [`alt` is mandatory on image buttons](https://html.spec.whatwg.org/multipage/input.html#attr-input-alt)… I'm taking that to another issue.

**Comment by giacomo-petri** [comment]
@Jym77, I've just mentioned our topic in WCAG. This in an interesting reading for points above (including the original intent of 4.1.1).

**Comment by Jym77** [comment]
Good find!
So this is indeed passing 4.1.1 😕
