### ISSUE TITLE
Element with lang attribute has valid language tag - Failed examples 4 and 5

### ISSUE THREAD

**Issue by giacomo-petri** [auto-wcag/auto-wcag#2063]
* **Rule Title**: Element with lang attribute has valid language tag
* **Rule ID**: #de46e4
* **Rule Url**: https://www.w3.org/WAI/standards-guidelines/act/rules/de46e4/

---

* **Issue description 1**: Failed Example 4 and 5 states:
    * > The lang attribute must be valid because the content is [visible](https://www.w3.org/WAI/standards-guidelines/act/rules/de46e4/#visible).
    * > and its [descendant](https://dom.spec.whatwg.org/#concept-tree-descendant) is not [visible](https://www.w3.org/WAI/standards-guidelines/act/rules/de46e4/#visible) though it is still [included in the accessibility tree](https://www.w3.org/WAI/standards-guidelines/act/rules/de46e4/#included-in-the-accessibility-tree).
* **Question 1**: While Failed Examples 4 and 5 accurately fulfill the rule description, applicability, and expectations, there is no explicit mention of "visibility" and "accessibility tree" within these three areas. Consequently, whether an element is visible but not included in the accessibility tree or visually not available but present in the accessibility tree is not directly relevant to the rule itself. Although providing clarification is necessary to avoid any potential misunderstandings, it may be beneficial to add some contextual information in the applicability or background notes regarding this choice.

---

* **Issue description 2**: 
    ```
    <style>.test:before {content: "Questa frase è scritta in italiano"}</style>
    <div class="test" lang="invalid"></div>
    ```
    The provided example appears to be currently inapplicable since the _div_ element is empty. However, the text added through CSS using the _content_ property is still visible and accessible within the accessibility tree.
* **Question 2**: 
    * should we specify in the inapplicable examples that this particular example is currently inapplicable? This approach acknowledges that the example does not fit the current applicability criteria.
    * OR should we include this example in the applicability section and create a corresponding failure? This highlights the scenario and explicitly identifies it as a failure.

**Comment by Jym77** [comment]
* Question 1: the visibility and inclusion in the accessibility tree is part of the "text inheriting its programmatic language" definition used in the Applicability. I guess we should update the example descriptions to use that term rather than "visible"/"included in the accessibility tree" (or in addition to).
* Question 2: Indeed, this is inapplicable for the rule, but applicable for the SC. This is not a problem as far as rule format is concerned. We may want to include pseudo-elements in this rule (and several others…) Another possibility would be to specifically have rules for pseudo-elements (which, e.g. would allow tools who cannot handle them to still claim implementation of the "basic" rules). This feels like a larger topic since no rule is currently handling pseudo-elements (or at least not explicitly). As a first step if we want to highlight that, we could add an Inapplicable example with pseudo-element text and a **correct** `lang` attribute (as Inapplicable examples must satisfy the SC); this would at least make it explicit that the rule is currently ignoring these and therefore partial.

**Comment by Jym77** [comment]
@giacomo-petri We've moved Question 2 as its own issue in #2073 since it may require some deeper discussions.

For question 1, it seems this "only" needs to update the example description with the correct terms.

**Comment by giacomo-petri** [comment]
PR for point 1 is already approved and merged. 
Point 2 is covered by another issue.
Closing this ticket.
