### ISSUE TITLE
SC2-4-6-descriptive-headings needs review

### ISSUE THREAD

**Issue by WilcoFiers** [auto-wcag/auto-wcag#343]
This rule was merged before it could be discussed on a call #284. Please leave comments about this rule in the thread below.

**Comment by annethyme** [comment]
The rule in question is now in a PR (https://github.com/auto-wcag/auto-wcag/pull/444) again due to findings reported in https://github.com/auto-wcag/auto-wcag/issues/424.

Since no comments where left in this thread the last 4.5 months, I hope it is okay that I close this thread, since reviews of the rule will be done in the new PR. 

@WilcoFiers, let me know if you disagree.
