### ISSUE TITLE
Alignment with ACT Rules Format on section names?

### ISSUE THREAD

**Issue by annethyme** [auto-wcag/auto-wcag#350]
ACT Rules Format (latest version, https://github.com/w3c/wcag-act/blob/master/act-rules-format.bs) has "Limitations, Assumptions or Exceptions". Auto-WCAG always has "Assumptions" only. 

Auto-WCAG has "Background" as a standard section in the template, a section that is never mentioned in ACT Rules Format.

I think we either need to:
a) Change the Auto-WCAG template to match the ACT Rules Format, or 
b) Suggest changes to the ACT Rules Format to accommodate the needs found when exercising the ACT Rules Format in the wild.

**Comment by nitedog** [comment]
Along the lines of updating the templates (and existing rules), I think we should also have an acknowledgements section instead of the list of contributors list at the top of the page. This new section would include:

- List of rule authors
- List of rule reviewers/contributors (maybe this can be automated?)
- Any other acknowledgements, such as EC funding or other support

**Comment by annethyme** [comment]
ACT Rules Format is in latest editor's draft (https://w3c.github.io/wcag-act/act-rules-format.html#act-rule-structure)  updated to have "Assumptions" and "Background". 

It now also has "Acknowledgements". Should we update Auto-WCAG template to reflect this?

**Comment by jkodu** [comment]
Similar to https://github.com/auto-wcag/auto-wcag/issues/239, hence closing the issue.
