### ISSUE TITLE
Should "Role has required states and properties" limit itself to only elements included in the accessibility tree?

### ISSUE THREAD

**Issue by kasperisager** [auto-wcag/auto-wcag#372]
Just what it says on the tin. For reference: https://auto-wcag.github.io/auto-wcag/rules/SC4-1-2-role-has-required-states-and-properties.html

**Comment by kasperisager** [comment]
Summoning @ShadowBB who brought this up during validation of our implementation of the rule.

**Comment by WilcoFiers** [comment]
Please provide motivation for this question. Why should this be changed? Where is this creating problems?

**Comment by kasperisager** [comment]
To sum it up in a question: Will an element with a semantic role ever cause accessibility issues if it lacks a required state or property but is not included in the accessibility tree? If not then the applicability of the rule ought to be limited.

**Comment by dd8** [comment]
What about ARIA tab panels? There is one active tab panel in the accessibility tree, but the other tabs are hidden, so not included in the accessibility tree until their tab is clicked

If you restrict checks to items currently in the accessibility tree you may have a non-functioning tab panel due to tabs without associated tabpanel roless, or tabpanels without required state (aria-hidden in the case of the non-visible tabs)

And the hidden tab panels may contain other widgets with ARIA roles if it's a tabbed form.

There are similar issues with other complex widgets like ARIA trees.

**Comment by kasperisager** [comment]
Whichever way we decide to go with this, we need to be consistent. If the general convention is, which it seems to be currently, that rules should not consider content not perceivable by the group of users potentially affected by the issue that the rule looks for, then a missing state or property on something that is not included in the accessibility is not an issue. 

How to deal with dynamic content is an entirely different question and something I believe should be up to the implementer of the rule, be it a tool or a methodology. There is nothing stopping someone from loading up a page, stepping through a rule for the initial page load, interacting with the page, and then stepping through the rule again for content that has changed.

**Comment by dd8** [comment]
Agreed on the consistency - this might affect a lot of rules

One thing that's difficult with ARIA tabs is that the ARIA relationships in tabs are designed to link from visible content (the tab) to hidden content (the tab panel) and there are back-links in the form of aria-labelledby from the tabpanel to the tab. This probably impacts on the owned elements definition as well, since aria-controls is used to links tabs to the hidden tabpanels

**Comment by dd8** [comment]
I think there are problems with the current accessibility tree definition, because it doesn't align with browser implementations.

In Firefox hidden elements *are* in the accessibility tree, but there's an associated visibility flag, which can be in 3 states: visible (0), INVISIBLE or OFFSCREEN
https://dxr.mozilla.org/mozilla-central/source/accessible/generic/Accessible.cpp#328

WebKit is similar and exposes an isVisible method on accessible objects.

**Note** in Chrome adding *any* ARIA attribute to an element adds the element to the accessibility tree:
https://chromium.googlesource.com/chromium/blink/+/master/Source/modules/accessibility/AXLayoutObject.cpp#699

**Comment by annethyme** [comment]
I am co-assigning this rule to myself since I am the owner of this rule inside the WAI-Tools project. It has a deadline of March 31.

**Comment by annethyme** [comment]
Being handled by https://github.com/auto-wcag/auto-wcag/pull/436
